{% set name = "jsii" %}
{% set version = "1.72.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsii-{{ version }}.tar.gz
  sha256: 6daf1c17362bd07c50c299e08d9a4454075550eb78e035a160ecf9ea68ded3cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    # Original requirement: >=21.2,==21.*
    - attrs >=21.2,<22.0
    - cattrs >=1.8,<22.2
    - publication >=0.0.3
    - python >=3.7
    - python-dateutil
    - typeguard >=2.13.3,<3
    - typing_extensions >=3.7,<5.0

test:
  imports:
    - jsii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/jsii
  summary: Python client for jsii runtime
  dev_url: https://github.com/aws/jsii.git
  license: Apache-2.0
  license_file: NOTICE

extra:
  recipe-maintainers:
    - manics
