{% set name = "jsii" %}
{% set version = "1.95.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsii-{{ version }}.tar.gz
  sha256: f2461a0c1fdd6bb400caac5825596b0068a8c3adb9184549366adcf272815172

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=62.2,<63.dev0
    - wheel >=0.37,<1.dev0
    - pip
  run:
    - python >=3.7
    - attrs >=21.2,<24.0
    - cattrs >=1.8,<23.2
    - importlib_resources >=5.2.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0
    - python-dateutil
    - typing_extensions >=3.7,<5.0
    # calls node CLI
    - nodejs >=16,<18

test:
  imports:
    - jsii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/jsii
  summary: Python client for jsii runtime
  dev_url: https://github.com/aws/jsii.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - manics
    - ocefpaf
