{% set name = "jsii" %}
{% set version = "1.80.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsii-{{ version }}.tar.gz
  sha256: 4da63ab99f2696cd063574460c94221f0a7de9d345e71dfb19dfbcecf8ca8355

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - attrs >=21.2,<23.0
    - cattrs >=1.8,<22.3
    - importlib_resources >=5.2.0
    - publication >=0.0.3
    - python >=3.7
    - python-dateutil
    - typeguard >=2.13.3,<3
    - typing_extensions >=3.7,<5.0

test:
  imports:
    - jsii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/jsii
  summary: Python client for jsii runtime
  dev_url: https://github.com/aws/jsii.git
  license: Apache-2.0
  license_file: NOTICE

extra:
  recipe-maintainers:
    - manics
