{% set name = "jsii" %}
{% set version = "1.118.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jsii-{{ version }}.tar.gz
  sha256: 711131f84a9e968e12b8a09449c734907ca53faa51bf5b85685976dff9faf554

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62.2,<63.dev0
    - wheel >=0.37,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=21.2,<24.0
    - cattrs >=1.8,<23.3
    - importlib_resources >=5.2.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0
    - python-dateutil
    - typing_extensions >=3.8,<5.0
    # calls node CLI
    - nodejs >=16

test:
  imports:
    - jsii
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aws/jsii
  summary: Python client for jsii runtime
  dev_url: https://github.com/aws/jsii.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - manics
    - ocefpaf
